### ISSUE TITLE
Improve module icon

### ISSUE THREAD

**Issue by vnadot** [NSenaud/vscode-epics#10]
background, resolution, new idea ? Actual icon is located in ```images/```

![image](https://user-images.githubusercontent.com/23168605/53949647-c5589880-40ca-11e9-8cc2-c4d10277acaa.png)
![image](https://user-images.githubusercontent.com/23168605/53949682-dbfeef80-40ca-11e9-9e64-db7d680cb72c.png)

**Comment by agaget** [comment]
Faudrait mettre un leger contour comme le gris clair du market place, ça le ferait ressortir sur un fond noir et serait invisible sur le market place

**Comment by agaget** [comment]
Je veux bien t'aider mais en vrai, j'ai trouvé un acronyme (ma passion), donc je vais surtout changer le logo. 
Enlight Your EPICS = EYE

**Comment by vnadot** [comment]
1fb17ea001b9a9160d12af3ae1ee67a134788483
