### ISSUE TITLE
add SNL snippet

### ISSUE THREAD

**Issue by agaget** [NSenaud/vscode-epics#19]
state name_state{
    when {
    } state state2
}

pvPut(pv_variable);
pvAssign(pv_variable",pv_name")
pvGet(pv_variable);

peut-être d'autres à voir dans la doc SNL, même si elles ne sont pas compliqués  mais l'idée est surtout de pouvoir retrouver les fonctions avec le nom genre epics.snl.*

**Comment by vnadot** [comment]
a31546e3af34a4fe2b72852b7483f42b2a0c3cec
