### ISSUE TITLE
add epicsType in c asub

### ISSUE THREAD

**Issue by agaget** [NSenaud/vscode-epics#20]
epics.type.Float32 -> epicsFloat32 var

avec tous les types EPiCS, trouvable dans le include/epicsType.h de la base (au moins 3.15.4)

**Comment by vnadot** [comment]
I've added the following types (in file epics-base/modules/libcom/src/misc/epicsTypes.h) :
- epicsInt8
- epicsUInt8
- epicsInt16
- epicsUInt16
- epicsEnum16
- epicsInt32
- epicsUInt32
- epicsInt64
- epicsUInt64
- epicsFloat32
- epicsFloat64
- epicsString

**Comment by vnadot** [comment]
0cc50c0513db74a793f861505bc71847edf9a66f
