### ISSUE TITLE
Snippet for Db/template doesn't work with v.0.4

### ISSUE THREAD

**Issue by agaget** [NSenaud/vscode-epics#7]

**Comment by agaget** [comment]
@vnadot

**Comment by agaget** [comment]
With old version of vscode, works fine with 1.3.1... retrocompatibility not really necessary so i close

**Comment by vnadot** [comment]
1.5 or **newer version**.

**Comment by agaget** [comment]
"OR" is inclusive, so it's a wrong info ! You fakenewser !
